Add filter to DataExtractor that removes some of control chars that XML transport doesn't support.
Fixes XML parser error in Solr
org.apache.solr.common.SolrException: Illegal character ((CTRL-CHAR, code
11))

Relevant issues: sunspot#570