Fix test failure
Tests where failing with the following

      NoMethodError:
       undefined method `password' for "http://solr.test/uri":String

             uri.password = "REDACTED" if uri.password
                                             ^^^^^^^^^
     # ./vendor/bundle/ruby/3.1.0/gems/rsolr-2.6.0/lib/rsolr/error.rb:9:in `clean_uri'
     # ./vendor/bundle/ruby/3.1.0/gems/rsolr-2.6.0/lib/rsolr/error.rb:27:in `to_s'
     # ./lib/sunspot/session_proxy/retry_5xx_session_proxy.rb:29:in `message'
     # ./lib/sunspot/session_proxy/retry_5xx_session_proxy.rb:29:in `rescue in method_missing'
     # ./lib/sunspot/session_proxy/retry_5xx_session_proxy.rb:16:in `method_missing'
     # ./lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `index'
     # ./lib/sunspot.rb:190:in `index'
     # ./spec/api/session_proxy/retry_5xx_session_proxy_spec.rb:49:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # FakeRSolrErrorHttp:
     #   A FakeRSolrErrorHttp for which `exception.message.to_s` raises NoMethodError.

This was triggered by the test suite providing a String object to the rsolr gem where it is
expecting a URI object.

Ref:
 - lib/sunspot/session_proxy/retry_5xx_session_proxy.rb:29 and 33
 - spec/api/session_proxy/retry_5xx_session_proxy_spec.rb:24
 - https://github.com/rsolr/rsolr/blob/master/lib/rsolr/error.rb#L6-L13