Sunspot::DSL::Search responds to only any_of
Updating readme to any_of instead of any as the DSL doesn't support any method. 

NoMethodError: undefined method `any' for #<Sunspot::DSL::Search:0x000000089d3b88>