Add filter to DataExtractor that removes some of control chars (#886)
* Add filter to DataExtractor that removes some of control chars that XML transport doesn't support.

Fixes XML parser error in Solr
org.apache.solr.common.SolrException: Illegal character ((CTRL-CHAR, code
11))

Relevant issues: sunspot#570

* Add support for earlier ruby versions (below 2.1)

* Replace the list of blacklisted chars with a regular expression. Should be more efficient on larger strings.

* Add tests