Fix travis error last comment and uninitialized constant r solr connection (#866)
* RSolr 2.0 is released so bundler automatically installs the latest version. Test also against older RSolr version.

* The method 'last_comment' which is called from rspec-core was removed from rake 11

* Fix Gem::InstallError: nokogiri ~> 1.7 requires Ruby version >= 2.1.0.

* rails 5.0 doesn't work with rspec-rails-2.14.2 undefined method 'alias_method_chain'